
project_id = "saowfbbgdknxucpuhopy"

[analytics]
enabled = true

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://saowfbbgdknxucpuhopy.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
enable_signup = true

[functions.openrouter-chat]
verify_jwt = false

[functions.run-prompt]
verify_jwt = true